import Head from 'next/head'
import Header from './component/header'
import Footer from './component/footer'
import Homepage from './home'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
       {/* <script src="https://cdn.jsdelivr.net/npm/react/umd/react.production.min.js" crossorigin></script> */}

      {/* <script
        src="https://cdn.jsdelivr.net/npm/react-dom/umd/react-dom.production.min.js"
        crossorigin></script> */}

      {/* <script
        src="https://cdn.jsdelivr.net/npm/react-bootstrap@next/dist/react-bootstrap.min.js"
        crossorigin></script> */}
      </Head>
      <main>
        <Header/>
        <Homepage/>
        <Footer/>
      </main>
    </>
  )
}
